# Generated by Django 5.0 on 2024-02-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0004_auto_20200814_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='break_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='break_start_2',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='break_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='break_time_2',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
