# Generated by Django 5.0 on 2024-02-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0005_class_break_start_class_break_start_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='no_sessions',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
