# Generated by Django 5.0 on 2024-02-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0006_class_no_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_mins',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
