# Generated by Django 5.0 on 2024-02-15 18:30

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0007_class_class_mins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='week_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=2000),
        ),
    ]
